name: Checks

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    container: ghcr.io/acts-project/format10:v11
    steps:
      - uses: actions/checkout@v3
      - name: Check
        run: .github/check_format.sh .
